Update the readme, and some workflow/values cleanup/prettying
honeycombio/raas-hnytest pull request #14
Opened 2024-07-26 18:39 UTC by tdarwin

## Short description of the changes

This is mostly to update the README with some more updated guidance on how users can use this Repo for managing and deploying Refinery and Refinery Monitoring on their own.

This also fixes the EU deploying of the k8s monitoring bits in the workflow, so that events are sent to the right Honeycomb instance, and it pretties up where the `nodeSelector` section of the values files are.

## How to verify that this has the expected result
No verification really needed here. It's just README's and no substantive changes to values or anything like that.

2024-07-26 18:53 UTC, mterhar requested changes
Turning the run-on into a quick list seems to be easier to grok

2024-07-26 18:53 UTC, mterhar commented on README.md
> +This repository is for deploying and managing Refinery on a Kubernetes cluster, as well as some additional monitoring functions for monitoring the use of Kubernetes resources as well as monitoring yo
```suggestion
This repository has terraform and helm configurations to:

1. Configure a Refinery cluster
1. Install the Refinery 
1. Install opentelemetry collectors into the cluster to observe health and performance
1. Use terraform to configure triggers in Honeycomb
1. The GitHub actions to handle deployment and reconfiguration
```

2024-08-01 19:34 UTC, irvingpop commented on README.md
> +This repository has terraform and helm configurations to:
I worry this might give the impression that we have both TF _and_ helm bits for installing/configuring Refinery.
```suggestion
This repository demonstrates best practices for using Helm to deploy Refinery, and Terraform to manage Honeycomb objects.
```

2024-08-01 19:36 UTC, irvingpop approved these changes
one minor wording nit to fix, but dropping an approval so you're not held up after that

2024-08-06 17:40 UTC, mterhar approved these changes

2024-08-07 12:06 UTC, merged